[package]
name = "rustscratchpad"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "two_sum"
path = "src/leetcode/1_two_sum.rs"

[[bin]]
name = "palindrome"
path = "src/leetcode/9_palindrome.rs"

[[bin]]
name = "118_pascals_triangle"
path = "src/leetcode/118_pascals_triangle.rs"

[dependencies]
