[package]
name = "rustscratchpad"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "two_sum"
path = "src/leetcode/1_two_sum.rs"

[[bin]]
name = "palindrome"
path = "src/leetcode/9_palindrome.rs"

[[bin]]
name = "pascals_triangle"
path = "src/leetcode/118_pascals_triangle.rs"

[[bin]]
name = "longest_common_prefix"
path = "src/leetcode/14_longest_common_prefix.rs"

[[bin]]
name = "valid_parentheses"
path = "src/leetcode/20_valid_parentheses.rs"

[dependencies]
